### ISSUE TITLE
Create docker to repeat this work

### ISSUE THREAD

**Issue by GuancongLuo** [jhaardt/wrs#1]
Hi, @jhaardt 

Thank you for sharing this interesting project.

I tried to reproduce the work, but I encountered a bug that I couldn't solve.

So I built the docker images([clarenceluo/wrs](https://hub.docker.com/repository/docker/clarenceluo/wrs)) on the basis of [ct2034/vnc-ros-kinetic-full](https://hub.docker.com/r/ct2034/vnc-ros-kinetic-full).

Please help us solve the problem of reproduction.

Thank you very much indeed!

**Comment by jhaardt** [comment]
Hi, thanks for the interest. I pulled your docker and found problems with loading the controller_manager. Is that the "bug that you couldn't solve"? I'm not 100% sure if it is a bug with my project, since when I try lunching the official UR demo `roslaunch ur_gazebo ur5.launch `. I still get the same errors and I never touched that code. Maybe its something with the Ros / Gazebo setup. I'm continue trying to figure it out, for a bit. I like the idea running it in a docker.

Edit: Yep, even a new workspace with only a freshly cloned official "universal_robot" git, spits out the same errors when trying to run the demo, so its not my project. It something with the docker/ROS setup.

**Comment by jhaardt** [comment]
Ok, I think I got it. It was indeed a problem with your docker, you need to `apt dist-upgrade` it. https://github.com/ridgeback/ridgeback_robot/issues/29

Edit: Ok, I did a final fresh pull of your docker and verified the missing `apt dist-upgrade`, you also need to install ros_conrol `sudo apt-get install ros-kinetic-ros-control ros-kinetic-ros-controllers`.
A suggestion to make your life easier is, to save the source setup.bash in the ~/.bashrc. https://answers.ros.org/question/206876/how-often-do-i-need-to-source-setupbash/

Hope that were all your bugs, your issue description was a bit vague.

**Comment by GuancongLuo** [comment]
Thank you very much for your help. It really solved the recurrence problem I encountered.

I only used `rosdep` to download the required packages, but I forgot `upgrade`.

I've uploaded a new docker version([clarenceluo/wrs:v2](https://hub.docker.com/layers/142729603/clarenceluo/wrs/v2/images/sha256-634efc89d70791620bdf1411cfd871a5bef2dbefb783d036bf537eb26b231341?context=explore)), and I think others can reproduce this interesting project.

In addition, I am also a master in the field of manipulator. I am very interested in manipulator operation tasks, especially grasping and assembling.

Can you read your paper and send it to my email(15161167879@163.com)? 

Thank you very much.

**Comment by shaashou** [comment]
> Thank you very much for your help. It really solved the recurrence problem I encountered.非常感谢您的帮助。它真的解决了我遇到的复发问题。
> 
> I only used `rosdep` to download the required packages, but I forgot `upgrade`.我只使用 `rosdep` 下载了所需的软件包，但我忘记了`升级 `。
> 
> I've uploaded a new docker version([clarenceluo/wrs:v2](https://hub.docker.com/layers/142729603/clarenceluo/wrs/v2/images/sha256-634efc89d70791620bdf1411cfd871a5bef2dbefb783d036bf537eb26b231341?context=explore)), and I think others can reproduce this interesting project.我已经上传了一个新的 docker 版本（[clarenceluo/wrs：v2](https://hub.docker.com/layers/142729603/clarenceluo/wrs/v2/images/sha256-634efc89d70791620bdf1411cfd871a5bef2dbefb783d036bf537eb26b231341?context=explore)），我想其他人可以重现这个有趣的项目。
> 
> In addition, I am also a master in the field of manipulator. I am very interested in manipulator operation tasks, especially grasping and assembling.此外，我还是机械手领域的高手。我对机械手作任务非常感兴趣，尤其是抓取和组装。
> 
> Can you read your paper and send it to my email([15161167879@163.com](mailto:15161167879@163.com))?您能阅读您的论文并将其发送到我的电子邮件 （[15161167879@163.com](mailto:15161167879@163.com)） 吗？
> 
> Thank you very much.  谢谢。

我在您的docker里面无法启动rviz这是什么呢

**Comment by shaashou** [comment]
> Thank you very much for your help. It really solved the recurrence problem I encountered.非常感谢您的帮助。它真的解决了我遇到的复发问题。
> 
> I only used `rosdep` to download the required packages, but I forgot `upgrade`.我只使用 `rosdep` 下载了所需的软件包，但我忘记了`升级 `。
> 
> I've uploaded a new docker version([clarenceluo/wrs:v2](https://hub.docker.com/layers/142729603/clarenceluo/wrs/v2/images/sha256-634efc89d70791620bdf1411cfd871a5bef2dbefb783d036bf537eb26b231341?context=explore)), and I think others can reproduce this interesting project.我已经上传了一个新的 docker 版本（[clarenceluo/wrs：v2](https://hub.docker.com/layers/142729603/clarenceluo/wrs/v2/images/sha256-634efc89d70791620bdf1411cfd871a5bef2dbefb783d036bf537eb26b231341?context=explore)），我想其他人可以重现这个有趣的项目。
> 
> In addition, I am also a master in the field of manipulator. I am very interested in manipulator operation tasks, especially grasping and assembling.此外，我还是机械手领域的高手。我对机械手作任务非常感兴趣，尤其是抓取和组装。
> 
> Can you read your paper and send it to my email([15161167879@163.com](mailto:15161167879@163.com))?您能阅读您的论文并将其发送到我的电子邮件 （[15161167879@163.com](mailto:15161167879@163.com)） 吗？
> 
> Thank you very much.  谢谢。

报错如下X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
