### ISSUE TITLE
Related theoretical articles

### ISSUE THREAD

**Issue by GuancongLuo** [jhaardt/wrs#2]
Thank you for sharing this interesting work.

But in the process of studying, I encountered the problem of incomplete theoretical foundation.

Do you have any articles or blogs about this work that you can recommend to me to learn？

**Comment by jhaardt** [comment]
Answered via email.

**Comment by NKU-ZiXuan** [comment]
> Answered via email.



> Answered via email.

I'm interested in your excellent, can you also share the articles or blogs about this work or your master's thesis with me？
Thank you！
My E-mail: 921218316@163.com
