### ISSUE TITLE
tf2_geometry_msgs 

### ISSUE THREAD

**Issue by zhengnx0906** [jhaardt/wrs#4]
‘TwistStamped’ is not a member of ‘tf2_geometry_msgs, but in std_msgs/ geometry_msgs

**Comment by jhaardt** [comment]
I haven't touched the code in a Year. And the information you provided are super vague. That's why I can't really help you much.

Did you try to run the docker, mentioned in another issue? Otherwise do you have the right ros version, updated dependencies...?

**Comment by zhengnx0906** [comment]
Thank you. The problem has been solved. Just add "include <geometry_msgs/TwistStamped.h&gt;".I tried to run through your sample code under ROS melodic, but I always couldn't find the hole, resulting in collision, and then the environment crashed. LOL



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月26日(星期六) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jhaardt/wrs] tf2_geometry_msgs  (Issue #4)





 
I haven't touched the code in a Year. And the information you provided are super vague. That's why I can't really help you much.
 
Did you try to run the docker, mentioned in another issue? Otherwise do you have the right ros version, updated dependencies...?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhengnx0906** [comment]
I didn't try to use docker. I think I'll take a closer look at the code first. Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jhaardt/wrs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月26日(星期六) 晚上6:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jhaardt/wrs] tf2_geometry_msgs  (Issue #4)





 
I haven't touched the code in a Year. And the information you provided are super vague. That's why I can't really help you much.
 
Did you try to run the docker, mentioned in another issue? Otherwise do you have the right ros version, updated dependencies...?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunnyandmorning** [comment]
> Thank you. The problem has been solved. Just add "include <geometry_msgs/TwistStamped.h&gt;".I tried to run through your sample code under ROS melodic, but I always couldn't find the hole, resulting in collision, and then the environment crashed. LOL
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月26日(星期六) 晚上6:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jhaardt/wrs] tf2_geometry_msgs (Issue #4) I haven't touched the code in a Year. And the information you provided are super vague. That's why I can't really help you much. Did you try to run the docker, mentioned in another issue? Otherwise do you have the right ros version, updated dependencies...? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Please,did you solve the environment crash problem?

**Comment by zhengnx0906** [comment]
Sorry, I haven't solved it yet and have moved on to other project. I guess one reason is that the contact force is too high.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月1日(星期三) 晚上7:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jhaardt/wrs] tf2_geometry_msgs  (Issue #4)





  
Thank you. The problem has been solved. Just add "include <geometry_msgs/TwistStamped.h&gt;".I tried to run through your sample code under ROS melodic, but I always couldn't find the hole, resulting in collision, and then the environment crashed. LOL
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年2月26日(星期六) 晚上6:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [jhaardt/wrs] tf2_geometry_msgs (Issue #4) I haven't touched the code in a Year. And the information you provided are super vague. That's why I can't really help you much. Did you try to run the docker, mentioned in another issue? Otherwise do you have the right ros version, updated dependencies...? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Please,did you solve the environment crash problem?
